import type { CutsRecord } from "@/features/cuts/model/types/CutsRecord.types";

// 백엔드 연동 전까지 화면 확인용으로 쓰는 더미 데이터
export const dummyCutsRecords: CutsRecord[] = [
  {
    id: "record-1",
    date: "2026-07-18",
    procedureName: "다운펌",
    salonName: "준오헤어 강남점",
    designerName: "오용준",
    rating: 5,
    thumbnailUrl: "",
    category: "펌",
    analysisStatus: "분석 완료",
    isSharing: true,
  },
  {
    id: "record-2",
    date: "2026-07-18",
    procedureName: "다운펌",
    salonName: "준오헤어 강남점",
    designerName: "오용준",
    rating: 5,
    thumbnailUrl: "",
    category: "펌",
    analysisStatus: "분석 완료",
    isSharing: false,
  },
  {
    id: "record-3",
    date: "2026-07-18",
    procedureName: "다운펌",
    salonName: "준오헤어 강남점",
    designerName: "오용준",
    rating: 5,
    thumbnailUrl: "",
    category: "펌",
    analysisStatus: "분석 중",
    isSharing: false,
  },
  {
    id: "record-4",
    date: "2026-07-18",
    procedureName: "다운펌",
    salonName: "준오헤어 강남점",
    designerName: "오용준",
    rating: 5,
    thumbnailUrl: "",
    category: "펌",
    analysisStatus: "재촬영",
    isSharing: false,
  },
  {
    id: "record-5",
    date: "2026-07-18",
    procedureName: "다운펌",
    salonName: "준오헤어 강남점",
    designerName: "오용준",
    rating: 5,
    thumbnailUrl: "",
    category: "펌",
    analysisStatus: "재촬영",
    isSharing: false,
  },
];
